services:
  server:
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/todolist
      - SPRING_DATASOURCE_USERNAME=springstudent
      - SPRING_DATASOURCE_PASSWORD=springstudent
  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=todolist
      - POSTGRES_USER=springstudent
      - POSTGRES_PASSWORD=springstudent
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U springstudent -d todolist"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:

