apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
  labels:
    app: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo
        image: blaenkner/todo:latest
        ports:
        - containerPort: 8080
        env:
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-user
        - name: USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: POSTGRES_URL
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: postgres-url
---
apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  type: NodePort
  selector:
    app: todo
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30100